### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by insoxin** [85Ryan/wp2wb#1]
头条文章可以设置截取多少字吗？(摘要)
对seo有好处
https://zhangge.net/4512.html

**Comment by 85Ryan** [comment]
WP 摘要函数不支持富文本格式，如果截取一定字数，头条文章的排版相对会比较乱、不好看，并不是一个好的选择。
如果希望博客引流，建议使用普通微博功能。

**Comment by insoxin** [comment]
建议增加设置，可以强制截取😂
